### ISSUE TITLE
Setup on GA

### ISSUE THREAD

**Issue by vnl** [HSAnet/qt-google-analytics#18]
Hello, 

Excellent example and thank you. However I do have issues testing this. I tried to run your example and as well as within my product. 
Change the GA ID and ran the executable. I unfortunately am not sure how to verify the data that is being sent. 
I do get a http 200 so the connection is made I think. So most of the work now is to see how the settings has to be made in GA. 

![image](https://user-images.githubusercontent.com/1355466/27915337-e5f38980-625d-11e7-9630-82d7240945ea.png)

Any help or suggestion would be greatly appreciated. Because the only options on GA is for web or for mobile app. I am working on a desktop application.

**Comment by Pflanzgurke** [comment]
Hi,
receiving an HTTP 200...seems like it worked. Sometimes the GA web interface only shows the data after a significant delay. Are you still seeing nothing in the interface?

**Comment by MKV21** [comment]
Also note that the default setting in the GA web interface "Last 7 days" does not include the current day.

**Comment by Pflanzgurke** [comment]
Since we didn't hear back, I assume it was not shown yet in the GA interface and therefore not a problem with the code.
