### ISSUE TITLE
Send "session start" on first request

### ISSUE THREAD

**Issue by theoriginalgri** [HSAnet/qt-google-analytics#2]
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#sc

**Comment by rggjan** [comment]
Partly solved (session start can be called manually) here: https://github.com/HSAnet/qt-google-analytics/pull/7

**Comment by rggjan** [comment]
Why was this closed? Is it implemented now?

**Comment by theoriginalgri** [comment]
No, it can be called manually as you suggested before.

Going this way we do not change behavior of the library, also the session start and end are optional anyway according to the documentation.
