### ISSUE TITLE
Package qt-google-analytics to be used with qt-pods

### ISSUE THREAD

**Issue by cybercatalyst** [HSAnet/qt-google-analytics#5]
See here for reference:
https://github.com/cybercatalyst/qt-pods

**Comment by theoriginalgri** [comment]
We're thinking about that when your project grows a little more mature like cocoapods or [inqlude](http://inqlude.org/contribute.html) (which does about the same as your project).

**Comment by cybercatalyst** [comment]
Hey there, thanks for considering  :)

I have added a section in the README that states why qt-pods technically is different than inqlude. Nevertheless I am willing to work with the inqlude guys, but nobody seems to be active there (at least noone answers mails).

If have helped a couple projects in the last days with onboarding, so if you need help, don't hesitate to ask. I am a bit careful doing it myself though, because I can't always know if I am not breaking existing stuff (like depended projects that rely on yours).
